name: books_storage
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.7 <3.0.0"

dependencies:
  books_api:
    path: ../books_api
  shared_preferences: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
